In [42]:
import pandas as pd
import numpy as np
import operator

import gensim
from gensim import corpora, models

import IPython
import pprint as pp

In [2]:
tf_idfMIMIC = pd.read_csv('../Dataset/MIMIC_TFIDF.csv', header=None)
embeddingMIMIC_500 = pd.read_csv('../Dataset/MIMIC_EMBEDDING_500.csv', header=None)
embeddingMIMIC_1000 = pd.read_csv('../Dataset/MIMIC_EMBEDDING_1000.csv', header=None)

IPython.display.display(tf_idfMIMIC.head())
print tf_idfMIMIC.shape
IPython.display.display(embeddingMIMIC_500.head())
print embeddingMIMIC_500.shape
IPython.display.display(embeddingMIMIC_1000.head())
print embeddingMIMIC_1000.shape

,0,1,2,3,4,5,6,7,8,9,...,58547,58548,58549,58550,58551,58552,58553,58554,58555,58556
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, ..."
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, ..."
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."

(9070, 58557)

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,500
0,-0.103543,-0.012502,-0.424144,0.212219,0.019946,-0.375629,-0.234059,-0.685255,0.258941,0.066841,...,0.203807,0.238108,0.207160,-0.141817,0.050257,-0.183560,0.330741,0.009931,-0.379063,"[1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, ..."
1,-0.160384,-0.220788,-0.103112,0.242240,-0.284538,-0.334619,-0.097042,-0.002679,0.130309,-0.069282,...,0.213276,-0.086477,-0.167185,-0.465966,0.055130,-0.012835,0.147294,0.071352,0.074858,"[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, ..."
2,-0.082104,-0.163777,-0.217164,-0.097709,-0.105277,-0.186383,-0.063181,-0.321840,0.113866,-0.023926,...,0.317707,-0.079929,-0.119824,-0.194287,0.022348,-0.106097,0.212797,0.249908,-0.119827,"[0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,-0.030222,0.312208,-0.166403,0.195136,-0.018125,-0.098916,0.098599,0.009624,-0.203354,0.219677,...,0.535848,0.167292,-0.248854,-0.178905,0.070832,0.151681,0.192916,0.001420,0.057674,"[0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
4,-0.219272,-0.124820,0.116468,-0.095367,0.025796,0.033337,0.008354,-0.271081,-0.196097,-0.033097,...,0.349481,0.241827,-0.061761,-0.478814,0.279882,0.020531,-0.077272,-0.066161,0.236716,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."

(9070, 501)

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,-0.233078,0.000059,0.139688,-0.020598,-0.093930,-0.533987,-0.405496,-0.814608,0.329403,0.053535,...,-0.328284,0.673627,0.149490,-0.556741,0.245821,0.204426,-0.100343,0.271253,0.219237,"[1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, ..."
1,-0.127616,0.304769,-0.176857,0.102086,-0.258765,-0.285830,0.232638,0.151294,-0.020478,-0.235782,...,0.190140,0.104561,0.012538,-0.520007,-0.281434,-0.406798,-0.180232,-0.090346,0.361563,"[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, ..."
2,-0.107864,-0.083938,-0.205035,-0.023672,-0.292592,-0.205047,0.009431,-0.391853,-0.045808,-0.271680,...,0.150131,0.492541,0.027230,-0.286698,0.369664,0.065249,-0.323563,0.625736,0.148084,"[0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,-0.107762,0.383690,-0.219993,0.329083,0.030215,-0.062234,0.425490,-0.346945,-0.509145,0.094985,...,-0.496814,-0.426172,0.127881,0.199794,0.284368,0.152260,-0.299348,0.802058,0.502197,"[0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
4,-0.403024,-0.044253,0.500976,0.112174,0.292022,-0.123792,-0.002551,-0.398680,-0.346838,-0.286207,...,-0.249512,-0.234318,0.321332,0.829054,0.095602,0.182005,0.526807,0.466212,0.310497,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."

(9070, 1001)

In [10]:
preprocessedMIMIC = pd.read_csv("../Dataset/Preprocessed_MIMIC.csv")
IPython.display.display(preprocessedMIMIC.head())
print preprocessedMIMIC.shape

,SUBJECT_ID,HADM_ID,ISERROR,TEXT,ICD9_CODE,ICD9_Classes,class_labels,PREPROCESSED_TEXT
0,29075,179159.0,NaN,67m w ho multiplemyeloma dx 2111 neuropathy be...,5789,9,"[1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, ...",67m w ho multiplemyeloma dx 2111 neuropathy be...
1,18082,181163.0,NaN,age 90 52f copd home o2 cad recurrent aspirati...,59010,10,"[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, ...",age 90 52f copd home o2 cad recurrent aspirati...
2,28742,185325.0,NaN,73 yo female breast cancer metastatic liverlun...,27652,3,"[0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...",73 yo female breast cancer metastatic liverlun...
3,31608,152365.0,NaN,title respiratory failure acute ardsdoctor las...,51881,8,"[0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...",title respiratory failure acute ardsdoctor las...
4,29076,193948.0,NaN,respiratory failure acute ardsdoctor last name...,51881,8,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",respiratory failure acute ardsdoctor last name...

(9070, 8)

In [19]:
preprocessedTextMIMIC = preprocessedMIMIC['PREPROCESSED_TEXT'].str.split(" ") 
IPython.display.display(preprocessedTextMIMIC.head())

0    [67m, w, ho, multiplemyeloma, dx, 2111, neurop...
1    [age, 90, 52f, copd, home, o2, cad, recurrent,...
2    [73, yo, female, breast, cancer, metastatic, l...
3    [title, respiratory, failure, acute, ardsdocto...
4    [respiratory, failure, acute, ardsdoctor, last...
Name: PREPROCESSED_TEXT, dtype: object

In [27]:
wordDictionary = gensim.corpora.Dictionary(preprocessedTextMIMIC)
idx = 0
for count, term in wordDictionary.iteritems():
    if idx < 10:
        print(count, term)
        idx += 1
wordDictionary.filter_extremes(no_below=10)

(4663, u'aaataa')
(54090, u'diseaseonly')
(27588, u'svglcx')
(29380, u'localizes')
(4021, u'symptomsadmitted')
(13128, u'uop60hr')
(27393, u'35mg')
(3980, u'clotted')
(2408, u'hanging')
(2924, u'woody')

In [29]:
bagOfWordsCorpus = [wordDictionary.doc2bow(tokensList) for tokensList in preprocessedTextMIMIC]
pp.pprint(bagOfWordsCorpus[0])

tfIdfModel = models.TfidfModel(bagOfWordsCorpus)
tfIdfCorpus = tfIdfModel[bagOfWordsCorpus]
pp.pprint(tfIdfCorpus[0])

[(0, 1),
 (1, 1),
 (2, 1),
 (3, 1),
 (4, 4),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1),
 (10, 1),
 (11, 2),
 (12, 1),
 (13, 1),
 (14, 1),
 (15, 1),
 (16, 1),
 (17, 1),
 (18, 1),
 (19, 3),
 (20, 1),
 (21, 1),
 (22, 1),
 (23, 1),
 (24, 1),
 (25, 1),
 (26, 2),
 (27, 2),
 (28, 1),
 (29, 2),
 (30, 2),
 (31, 2),
 (32, 1),
 (33, 1),
 (34, 1),
 (35, 2),
 (36, 1),
 (37, 1),
 (38, 1),
 (39, 2),
 (40, 2),
 (41, 1),
 (42, 2),
 (43, 1),
 (44, 1),
 (45, 1),
 (46, 1),
 (47, 2),
 (48, 1),
 (49, 1),
 (50, 2),
 (51, 1),
 (52, 1),
 (53, 1),
 (54, 1),
 (55, 1),
 (56, 1),
 (57, 2),
 (58, 1),
 (59, 2),
 (60, 2),
 (61, 2),
 (62, 1),
 (63, 4),
 (64, 3),
 (65, 1),
 (66, 1),
 (67, 1),
 (68, 1),
 (69, 4),
 (70, 1),
 (71, 1),
 (72, 1),
 (73, 1),
 (74, 2),
 (75, 1),
 (76, 1),
 (77, 1),
 (78, 1),
 (79, 1),
 (80, 1),
 (81, 1),
 (82, 1),
 (83, 2),
 (84, 1),
 (85, 2),
 (86, 3),
 (87, 2),
 (88, 1),
 (89, 1),
 (90, 1),
 (91, 1),
 (92, 2),
 (93, 1),
 (94, 1),
 (95, 1),
 (96, 1),
 (97, 1),
 (98, 1),
 (99, 2),
 (100, 3),
 (101, 2),
 (102, 1),
 (103, 1),
 (104, 1),
 (105, 1),
 (106, 1),
 (107, 1),
 (108, 1),
 (109, 1),
 (110, 1),
 (111, 1),
 (112, 2),
 (113, 1),
 (114, 2),
 (115, 1),
 (116, 1),
 (117, 1),
 (118, 1),
 (119, 1),
 (120, 1),
 (121, 1),
 (122, 1),
 (123, 1),
 (124, 1),
 (125, 1),
 (126, 1),
 (127, 1),
 (128, 1),
 (129, 4),
 (130, 1),
 (131, 1),
 (132, 1),
 (133, 1),
 (134, 1)]
[(0, 0.049201141453275005),
 (1, 0.11850518384559719),
 (2, 0.11059622468093558),
 (3, 0.11618930117510354),
 (4, 0.07471740923188984),
 (5, 0.121152966220655),
 (6, 0.11850518384559719),
 (7, 0.056371332872304544),
 (8, 0.06344922092110625),
 (9, 0.07222133354222639),
 (10, 0.08303653266398546),
 (11, 0.06443595755632889),
 (12, 0.060651007535283186),
 (13, 0.054187234274185335),
 (14, 0.05684969567611825),
 (15, 0.04299625002168292),
 (16, 0.11731103324219863),
 (17, 0.059194971382825895),
 (18, 0.018595565391640104),
 (19, 0.11791800763701625),
 (20, 0.10980874786332641),
 (21, 0.121152966220655),
 (22, 0.04753057183791891),
 (23, 0.050623979354983285),
 (24, 0.0526154601066964),
 (25, 0.11731103324219863),
 (26, 0.061121115683575464),
 (27, 0.13158899325562776),
 (28, 0.03382159627059657),
 (29, 0.08126525470050747),
 (30, 0.08464222065520695),
 (31, 0.05737997049353116),
 (32, 0.06659751036161485),
 (33, 0.08377674786610138),
 (34, 0.10630721972054495),
 (35, 0.23237860235020708),
 (36, 0.11513170405057715),
 (37, 0.03160001332138976),
 (38, 0.028262208136407077),
 (39, 0.05337346489361506),
 (40, 0.15681330095049414),
 (41, 0.09000246418723636),
 (42, 0.18826253954217706),
 (43, 0.031056586364034675),
 (44, 0.07614901853280101),
 (45, 0.0655109215385237),
 (46, 0.033148688936103086),
 (47, 0.07661839066355815),
 (48, 0.0629524686053541),
 (49, 0.04815325969384748),
 (50, 0.10311961987972337),
 (51, 0.05043613091507496),
 (52, 0.07142964433702802),
 (53, 0.025532539121552025),
 (54, 0.0655109215385237),
 (55, 0.05734075474190916),
 (56, 0.12263398942944938),
 (57, 0.06279705542150761),
 (58, 0.051995192672303854),
 (59, 0.0786803445841019),
 (60, 0.10093461369799511),
 (61, 0.02660099208144829),
 (62, 0.09316568135135066),
 (63, 0.07043230046338947),
 (64, 0.09369684898459962),
 (65, 0.06848078663884262),
 (66, 0.07133302316495756),
 (67, 0.027194172721856792),
 (68, 0.02594245647162456),
 (69, 0.09793761593043727),
 (70, 0.08897426009892397),
 (71, 0.04525388196412897),
 (72, 0.06586607471477901),
 (73, 0.10230646248445421),
 (74, 0.028463907491554877),
 (75, 0.07854843593843397),
 (76, 0.04644489408691522),
 (77, 0.07577771017147705),
 (78, 0.047187671274109624),
 (79, 0.04025148473133616),
 (80, 0.09316568135135066),
 (81, 0.03148780611028931),
 (82, 0.07869131628090197),
 (83, 0.07393608723436212),
 (84, 0.03214828787692235),
 (85, 0.08980820009347579),
 (86, 0.11635285542291027),
 (87, 0.11849009390881386),
 (88, 0.08340293894224837),
 (89, 0.05965060647610246),
 (90, 0.0792741333583962),
 (91, 0.043849069740888806),
 (92, 0.04486813809411431),
 (93, 0.06027611660140643),
 (94, 0.0461213648472781),
 (95, 0.072322719617299),
 (96, 0.019184447067935328),
 (97, 0.02116207256129566),
 (98, 0.10448579167607568),
 (99, 0.16535448304457226),
 (100, 0.2640005931286107),
 (101, 0.11653682657516606),
 (102, 0.07459121964370254),
 (103, 0.1003569860922235),
 (104, 0.1033640596089806),
 (105, 0.08641001245900547),
 (106, 0.023543375143448106),
 (107, 0.0696749372422412),
 (108, 0.07358477089288253),
 (109, 0.11978175290333444),
 (110, 0.036581001570533754),
 (111, 0.05496641939889048),
 (112, 0.186963956308844),
 (113, 0.04750396807718095),
 (114, 0.08111884175061762),
 (115, 0.06086869136849661),
 (116, 0.020146850847680788),
 (117, 0.07039358727594203),
 (118, 0.04023352945345393),
 (119, 0.10905342207449427),
 (120, 0.04710943474145351),
 (121, 0.03918690292816888),
 (122, 0.08474570811498856),
 (123, 0.06276957177112347),
 (124, 0.05268567997240073),
 (125, 0.05040500742177244),
 (126, 0.022427212307158176),
 (127, 0.12424395331618335),
 (128, 0.11059622468093558),
 (129, 0.12813086612201502),
 (130, 0.057431455474539844),
 (131, 0.029687715138116865),
 (132, 0.02650638237169618),
 (133, 0.09698350629720347),
 (134, 0.09777098311481262)]

In [32]:
# truncation of 150 by default
bagOfWordsHDP = gensim.models.HdpModel(corpus=bagOfWordsCorpus, id2word=wordDictionary)
tfIdfHDP = gensim.models.HdpModel(corpus=tfIdfCorpus, id2word=wordDictionary)

In [37]:
bagOfWordsHDP.optimal_ordering()
tfIdfHDP.optimal_ordering()

bagOfWordsHDP.save(fname_or_handle="models/bagOfWordsHDP")
tfIdfHDP.save(fname_or_handle="models/tfIdfHDP")

In [39]:
pp.pprint(bagOfWordsHDP.print_topics(num_topics=5, num_words=10))
pp.pprint(tfIdfHDP.print_topics(num_topics=5, num_words=10))

[(0,
  u'0.007*patient + 0.006*given + 0.006*ha + 0.005*last + 0.005*bp + 0.004*continue + 0.004*o2 + 0.004*monitor + 0.004*iv + 0.004*2'),
 (1,
  u'0.007*given + 0.006*patient + 0.005*continue + 0.005*monitor + 0.005*last + 0.004*gtt + 0.004*ha + 0.004*iv + 0.004*w + 0.004*bp'),
 (2,
  u'0.003*given + 0.003*hct + 0.003*ha + 0.003*w + 0.003*ed + 0.002*bleed + 0.002*hr + 0.002*iv + 0.002*unit + 0.002*cont'),
 (3,
  u'0.002*monitor + 0.002*ha + 0.002*bp + 0.002*continue + 0.002*cont + 0.002*iv + 0.002*w + 0.002*given + 0.002*fever + 0.002*last'),
 (4,
  u'0.003*patient + 0.002*o2 + 0.002*bp + 0.002*meql + 0.002*ha + 0.002*transferred + 0.002*valuable + 0.002*mgdl + 0.002*last + 0.002*heart')]
[(0,
  u'0.001*140180 + 0.001*whole + 0.001*denies + 0.001*aspiration + 0.001*somnolent + 0.001*left + 0.001*7080s + 0.001*224 + 0.001*513 + 0.001*metastasis'),
 (1,
  u'0.001*1uprbc + 0.001*adm + 0.001*ativan + 0.001*2 + 0.001*history + 0.001*hive + 0.001*nail + 0.001*eeg + 0.001*wth + 0.001*bair'),
 (2,
  u'0.001*72 + 0.001*encephalitis + 0.001*follows + 0.001*integrellin + 0.001*none + 0.001*game + 0.001*10mg + 0.001*cefazolin + 0.001*supposed + 0.001*rewarm'),
 (3,
  u'0.001*gallstone + 0.001*midnight + 0.001*esld + 0.001*occurred + 0.001*recovered + 0.001*living + 0.001*yearold + 0.001*recollection + 0.001*polymicrobial + 0.001*tremens'),
 (4,
  u'0.001*100110 + 0.001*pao2 + 0.001*dnr + 0.001*bun + 0.001*relatively + 0.001*pta + 0.001*liquid + 0.001*start + 0.001*considered + 0.001*chemoradiation')]

In [49]:
def LDAasLSI(threshold=0.7, maxIterns=5):
    topTopics = [(0, 0)]
    while topTopics[0][1] < threshold and maxIterns > 0:
        bagOfWordsLDA = gensim.models.LdaModel(corpus=bagOfWordsCorpus, id2word=wordDictionary)
        coherenceValues = {}
        for idx, topic in bagOfWordsLDA.show_topics(num_topics=-1, formatted=False):
            topic = [token for token, score in topic]
            coherenceModel = gensim.models.CoherenceModel(topics=[topic], window_size=10, dictionary=wordDictionary, texts=preprocessedTextMIMIC)
            coherenceValues[idx] = coherenceModel.get_coherence()
        topTopics = sorted(coherenceValues.items(), key=operator.itemgetter(1), reverse=True)
        maxIterns -= 1
    return bagOfWordsLDA, topTopics, threshold

bagOfWordsLDA, topTopicsLDA, threshold = LDAasLSI(0.9, 10)
bagOfWordsLDA.save(fname='LDAasLSI')
print threshold
print topTopicsLDA[:5]

0.9
[(17, 0.7558109094089935), (85, 0.671550485395678), (52, 0.6632950215074327), (77, 0.6112831177450407), (90, 0.603068509721977)]

In [53]:
# statistics of clusters selected by the models
print "1. Number of 'tfIdf' clusters         = %s" %(tf_idfMIMIC.shape[1] - 1)
print "2. Number of 'doc2vec500' clusters    = %s" %(embeddingMIMIC_500.shape[1] - 1)
print "3. Number of 'doc2vec1000' clusters   = %s" %(embeddingMIMIC_1000.shape[1] - 1)
print "4. Number of 'bagOfWordsHDP' clusters = %s" %(len(bagOfWordsHDP.show_topics(num_topics=-1)))
print "5. Number of 'tfIdfHDP' clusters      = %s" %(len(tfIdfHDP.show_topics(num_topics=-1)))
print "6. Number of 'bagOfWordsLDA' clusters = %s\n" %(len(bagOfWordsLDA.show_topics(num_topics=-1)))

# verify the topics for creating datasets
print sorted(bagOfWordsHDP[bagOfWordsCorpus[0]])

1. Number of 'tfIdf' clusters         = 58556
2. Number of 'doc2vec500' clusters    = 500
3. Number of 'doc2vec1000' clusters   = 1000
4. Number of 'bagOfWordsHDP' clusters = 150
5. Number of 'tfIdfHDP' clusters      = 150
6. Number of 'bagOfWordsLDA' clusters = 100

[(0, 0.7635890098498844), (2, 0.04159490572222007), (91, 0.1912597085417979)]

In [81]:
def generateDatasets(corpus, model, numClusters, datasetName):
    clusterList = []
    for idx in range(len(preprocessedTextMIMIC)):
        textClusters = [0] * numClusters
        clusters = model[corpus[idx]]
        for clusterNumber, probability in clusters:
            textClusters[clusterNumber] = probability
        textClusters.append(preprocessedMIMIC.iloc[idx, 6])
        clusterList.append(textClusters)
    pd.DataFrame(clusterList).to_csv(datasetName, index=False)
    
generateDatasets(corpus=bagOfWordsCorpus, model=bagOfWordsHDP, numClusters=150, datasetName='../Dataset/bagOfWordsHDP.csv')
generateDatasets(corpus=tfIdfCorpus, model=tfIdfHDP, numClusters=150, datasetName='../Dataset/tfIdfHDP.csv')
generateDatasets(corpus=bagOfWordsCorpus, model=bagOfWordsLDA, numClusters=100, datasetName='../Dataset/bagOfWordsLDAasLSI.csv')